[
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Ride",
        "distance": 20328.0,
        "moving_time": 4542,
        "elapsed_time": 4827,
        "total_elevation_gain": 112.5,
        "type": "Ride",
        "workout_type": null,
        "id": 4128854658,
        "external_id": "garmin_push_5608616453",
        "upload_id": 4417910629,
        "start_date": "2020-09-29T15:30:45Z",
        "start_date_local": "2020-09-29T10:30:45Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242832,
            -97.762404
        ],
        "end_latlng": [
            30.242816,
            -97.76232
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242832,
        "start_longitude": -97.762404,
        "achievement_count": 2,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 2,
        "photo_count": 0,
        "map": {
            "id": "a4128854658",
            "summary_polyline": "uxqwD`fusQwBaAa@o@Ke@[_@uRaKeBiAKHoAfGUCiCwAGOBg@OWuBiAeB{@mIsCoN_IaJqDwI_FgJaFaAQsClKmAKs@W_B^uAe@oAAQI]m@UQs@GgA]YBYXMI@QGGa@z@m@Xg@f@w@pDsAhC_@pBkAnByB|FWrB}AjEFbAl@nArC~HzA~CATsAj@gB{CyBsFaAqA_@PiAfBe@hBw@vBkBfJe@bBcArB[vBs@pBi@hCqA|CuDnEmEvHWR}@Jg@ReAl@DX@GSWeH}Ee@a@EQTy@|B_DlAyBVUlDb@~@^r@c@z@}AnAkDrAeBbBiEd@m@`@_Ab@k@v@kCVgB\\eAb@kCh@eBDc@MeAHa@pCiIv@gBZyAxBoEfBkFv@eBhAiEXeBb@wAb@aEA}B\\oBNYr@]d@iAz@{@hAuD\\_BGU{@]FiAdAgDxAsFJyBN{@xAoEr@oA|@y@f@yBxAgCZw@zCcDZ_ALsAd@sBb@]h@CZJf@j@z@sAhAZtAc@xAHvAKt@c@BQOGTDd@S~AKzHwCtBW~AkAf@w@tAk@z@s@vA_Cp@i@lBoB~B_Gl@g@N_BpCqL`A}CrBiEbAmE?uAJk@rBsFh@}C`BoCZuAG]o@}@Ig@@gAh@oDCe@We@Ge@y@e@_Ek@c@s@OG}@LWCKU?Yl@}DC[mJiDReAAw@X{@d@iCBa@I{@B_@Pa@\\MdBVJW@iAOsBa@qDEmHgCoACULqDk@IEUHSMACFXAFd@KFGC?c@ZIzQdAnBnAV\\^bA\\^jAj@dANx@Xp@j@jA~An@^fB`Af@FrAEz@N~@l@Nf@TpEAvAPxBcA|Dy@tAUhAUhBwA`EcC|BUf@CdBZ|Em@fIi@dBm@nAw@^UXIn@T`A?\\_AtDgApDm@jAsA|@a@|Am@t@y@tBc@vBi@xAi@z@GzCShAuA`CRJEFPPOM{@TSZBP[h@UnAaB~EAdBk@vAk@r@Q|@{@~BiAxA?~@Ij@LT`@RfDoB^bAlBhA~@dB`BnAb@NnC?JTLbBnBlAfA~@a@jBHIEGEHi@|AfBl@`AdAnAl@?TYj@S`Ba@bBa@xCYhAmAtDcAfGiA~EKlBVTlE|@bNtDDb@}@~F@d@hIfEC\\oAbDsAxAe@z@_@nAF?UrAcApDsArHFX|@p@lDjBxA`Af@hAXVt@Xt@B",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4417910629",
        "average_speed": 4.476,
        "max_speed": 10.8,
        "average_temp": 25,
        "average_watts": 63.3,
        "kilojoules": 287.4,
        "device_watts": false,
        "has_heartrate": true,
        "average_heartrate": 119.0,
        "max_heartrate": 143.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 171.6,
        "elev_low": 131.1,
        "pr_count": 1,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Run",
        "distance": 1622.5,
        "moving_time": 699,
        "elapsed_time": 763,
        "total_elevation_gain": 34.0,
        "type": "Run",
        "workout_type": null,
        "id": 4128848595,
        "external_id": "garmin_push_5608610619",
        "upload_id": 4417904471,
        "start_date": "2020-09-29T14:47:21Z",
        "start_date_local": "2020-09-29T09:47:21Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.2428,
            -97.76228
        ],
        "end_latlng": [
            30.24127,
            -97.768748
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.2428,
        "start_longitude": -97.76228,
        "achievement_count": 1,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4128848595",
            "summary_polyline": "oxqwDfeusQFRt@R~@^hAn@t@t@TV?HLJ~@^hAN@HRTb@@PHXPVHh@\\`B|@zAn@xBpA|An@dCr@v@b@LTAF[Ra@`@MZEVAR@d@FZZn@JJ@L]x@UJYEWKg@]}Ao@qAq@eBq@YQmB_Aq@[G?CDa@`BmAbE_@|Am@pBMLk@L",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4417904471",
        "average_speed": 2.321,
        "max_speed": 3.2,
        "average_cadence": 85.7,
        "average_temp": 24,
        "has_heartrate": true,
        "average_heartrate": 141.3,
        "max_heartrate": 163.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 156.4,
        "elev_low": 121.4,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Afternoon Ride",
        "distance": 21287.6,
        "moving_time": 3859,
        "elapsed_time": 3927,
        "total_elevation_gain": 377.0,
        "type": "Ride",
        "workout_type": null,
        "id": 4125076271,
        "external_id": "garmin_push_5604721729",
        "upload_id": 4413876526,
        "start_date": "2020-09-28T18:43:35Z",
        "start_date_local": "2020-09-28T13:43:35Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242862,
            -97.762353
        ],
        "end_latlng": [
            30.242758,
            -97.762331
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242862,
        "start_longitude": -97.762353,
        "achievement_count": 26,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4125076271",
            "summary_polyline": "{xqwDveusQmBo@m@wAYYiOkImAi@eDkBmCaB}CaBw@IcADeCa@QLo@rBILWAcCcAuAaAuB}@eJkFqHqCyTyLWMDHe@ImCfKIDsASk@UU?eA^WAuAe@gA?q@}@UOo@EeA[U@a@VGCE[yBzGM@Ca@QNyApDm@pBi@z@uCxHQhAcBzECTLbAz@nCfA~BjA~Cr@fAX|@oAn@QK{EqKq@{@_@JsAhBaBtFuA`H_@rAiBrEGtAg@nAq@pC}BfFaChCwE~H[TgB`@qAv@O@kHoFMW?YTw@lEeHd@EfCd@lA^f@YjAwBvA{DfAsAxAoDp@aALc@l@cAbAqDlAsGf@gB@i@E{AXm@TgAfAeCf@_Bt@oAf@sBf@y@tAcDzC}IbAeEJaAb@iB`@cDFqBXgC`Au@l@sAt@y@hAmD\\_BISw@YCKn@gDHOVGNYf@mD`@kB@}ARoAzByFtAsA\\uAzByER]~AoAn@{@VkAZeBPyAd@Y^Ej@Lh@j@|@sA`A`@vAc@jDAbBcAbC[`DqAvBk@jBYpB}Aj@}@tBiAfAqAt@mAnCqCpB{EdAeBfAuFpAmFx@kCt@yAhA_D~@oE@kAF_@xBwFf@_DpA}B\\gAD_@Kk@g@s@KaAH}@`@kBHeBEUqAcAkEo@q@y@aBFKY@Sr@aEEa@wE}AuCiANqA@s@Ty@n@iDKeA@QXe@RGlBVLQBi@KyB]sBK_BIkH{Ao@i@a@Ca@FeDg@ICWPUjRrAlBnAt@zAf@f@nAj@z@Hv@Vv@r@v@dAfBlAtAl@lBIlAVh@f@Rn@PhDAxBR`C_AhDeAhBOx@SzByAtD[`@kBzAUp@A~A\\jEe@tHaBzEs@ZYZIh@R`A?`@qBzGe@vBc@d@gAl@m@lBi@l@m@bBg@zBo@bBi@p@IpDIj@e@pAk@|@_Bz@w@vDiAbEAhBg@vAk@r@Ir@}@pCsB`CoARwBdBuA~@qEzBe@x@OlAUTi@NiB@cFd@cCHuCb@aCv@u@ZaDrB{@v@aAtA[x@aBvGy@|EgBtAMJGb@GnADXrArA|Af@RfAOt@gAzA_@~@?LVb@Mn@o@rAARRhAr@d@dBhCtAzAnAgA`AMTBNHCb@rCpAnBnAvBfAbJdFnI|CbHlDrGrDvKfEbCvAHNAb@FNhPdJZ?P]bAaF^OdBlArBbArA~@b@dAX^x@^|@F",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4413876526",
        "average_speed": 5.516,
        "max_speed": 10.6,
        "average_temp": 28,
        "average_watts": 146.8,
        "kilojoules": 566.6,
        "device_watts": false,
        "has_heartrate": true,
        "average_heartrate": 146.5,
        "max_heartrate": 174.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 121.4,
        "elev_low": 0.2,
        "pr_count": 12,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Lunch Walk",
        "distance": 1863.9,
        "moving_time": 1731,
        "elapsed_time": 1780,
        "total_elevation_gain": 22.0,
        "type": "Walk",
        "id": 4124440386,
        "external_id": "garmin_push_5604025795",
        "upload_id": 4413209921,
        "start_date": "2020-09-28T16:47:22Z",
        "start_date_local": "2020-09-28T11:47:22Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.25683,
            -97.755253
        ],
        "end_latlng": [
            30.24283,
            -97.76225
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.25683,
        "start_longitude": -97.755253,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 2,
        "photo_count": 0,
        "map": {
            "id": "a4124440386",
            "summary_polyline": "eptwDjyssQHDBHPNd@Jf@Xr@VTVZR^L`@Vf@Jp@ZrBl@LDJHH@LJXJh@Z^Zp@XPLDF`Al@?Ah@TxA|@~@\\~@b@j@b@RJ\\L\\DVLNNFBt@N`@LLHT@^VCBJEl@TRLND^Xt@ZDBFPLFb@JPP`@l@XTVLz@b@RP~Az@^PhAn@nB~@ZJDEJm@^gAAKHYFa@DCCIHIJUZEP^PH\\D\\Zj@\\JJZNNPd@T`AVvA|@JXBVf@p@z@Z^JLATOGCE@AB",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4413209921",
        "average_speed": 1.077,
        "max_speed": 1.7,
        "average_cadence": 55.2,
        "average_temp": 30,
        "has_heartrate": true,
        "average_heartrate": 110.0,
        "max_heartrate": 152.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 172.4,
        "elev_low": 103.4,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Run",
        "distance": 6477.1,
        "moving_time": 3049,
        "elapsed_time": 3116,
        "total_elevation_gain": 69.0,
        "type": "Run",
        "workout_type": null,
        "id": 4124294672,
        "external_id": "garmin_push_5603867082",
        "upload_id": 4413057121,
        "start_date": "2020-09-28T15:54:56Z",
        "start_date_local": "2020-09-28T10:54:56Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242995,
            -97.7623
        ],
        "end_latlng": [
            30.256869,
            -97.755251
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242995,
        "start_longitude": -97.7623,
        "achievement_count": 1,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 2,
        "photo_count": 0,
        "map": {
            "id": "a4124294672",
            "summary_polyline": "uyqwDjeusQi@MQKSK[_@Um@]YmC_BuCyAMMi@YuBsAeAe@WGSKAE}@k@]O_@YU@UFi@jBMx@_@~AAP]nAIj@Uv@Kr@EHaAvF_A|DIv@[jBMd@Yt@Mf@Ad@DnAHVTnBPhA@PIFJ^GDGEOBE?YHc@~@Kb@UVG\\MZU`@Ob@sAdBcCvGQT[p@sAzDi@fA}@fCo@rACESOw@g@kBw@qEsCiDmBSQo@Ym@i@UMSIUCOA}@De@R[VY\\OXc@nAa@r@a@lAQV]NS@k@C}@BOG]Yk@s@[U{@}@s@oAe@_@e@i@k@c@eAc@YGC@}AjAy@x@UXADKAoByAO[A_AGk@Qg@S[]oASqAI}AQWYAYL]DI[Ai@FYl@YFGLYAWm@i@_A}AYUSYQc@Og@c@gCu@kBW_AOWEWA_@K_@EUO]g@cAiAmCOc@WcAS]eAcCe@}A]}@G}@JYTYLc@Fc@d@eARy@@m@FUXq@NWdAiCX_APe@VWJYNaATk@VUJSTy@NU\\gAFeAJc@T_@VKr@g@Lg@GgAE]EGJXF^HJ`@PHCXk@|@}B@c@Fe@`@_AvB{Dh@g@TMNJFt@TV\\RZh@v@r@RFZXTn@HLZRHJHANQD?Rc@ZWPFf@RH^FLBENF|@RTL`@JLFt@h@h@XnAx@j@Zd@Px@j@|Ax@HH?B",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4413057121",
        "average_speed": 2.124,
        "max_speed": 3.9,
        "average_cadence": 85.6,
        "average_temp": 26,
        "has_heartrate": true,
        "average_heartrate": 144.0,
        "max_heartrate": 165.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 135.6,
        "elev_low": 81.2,
        "pr_count": 1,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Lunch Ride",
        "distance": 15976.7,
        "moving_time": 3786,
        "elapsed_time": 4003,
        "total_elevation_gain": 97.7,
        "type": "Ride",
        "workout_type": null,
        "id": 4120679616,
        "external_id": "garmin_push_5599968477",
        "upload_id": 4409185572,
        "start_date": "2020-09-27T16:09:45Z",
        "start_date_local": "2020-09-27T11:09:45Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242815,
            -97.762396
        ],
        "end_latlng": [
            30.242821,
            -97.762189
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242815,
        "start_longitude": -97.762396,
        "achievement_count": 2,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 2,
        "photo_count": 0,
        "map": {
            "id": "a4120679616",
            "summary_polyline": "qxqwD~eusQ{B{@U]Qo@m@i@gUiMi@QuGyDm@MoABiC_@aDWWDk@nASD_HcEiFsC{HqCiLeGkHaEo@QI?ITiAjFm@tBMN_AM{@Y[BgA\\e@Gi@Y_BCOIYo@SOeAIWQWGY@WVK@IGAUgAnCc@zAe@~@]Vs@ImAg@gBuAc@m@o@i@UH?ZPJTKBQEMKCMRa@nBFHFCNc@T}@EQZu@\\mBZmCCcB^{BLWn@]h@mAz@y@fAgD\\yAD_@CGy@]EKl@}Cd@iAX}A`A{CGaBVaBX{@d@{@XkAVk@`BiBJw@`@iAvB}DxBkCd@_Ah@_CFs@\\e@b@Or@H`@h@JB|@qAfA\\hAe@`BDnAGdBeAxAGt@QhAg@VUdBa@hAe@xAMn@m@v@c@`AoAbAa@~@o@r@y@h@cA|@w@f@y@z@q@l@_Bh@cABYd@_@L]b@m@PyAl@uB|@kE~A{Fx@_Bp@sBd@iBf@cC?aANs@rBcFh@eDhAoB^eAHc@A_@q@kAG}@@i@j@uC?i@Ka@gAk@eEsAeBTk@i@kAg@CSjBcHJKLDC`@UD_DkAqA[cBq@OGAKFe@DkA\\eAd@uCIkAD_@Ve@RGpAVRAJUDsAMcBa@oCEwIOMqAe@i@[CYLwA?oAGKe@EAYLStMv@xCXnBnA~@fB`@^n@XbBTp@ZfAdAl@bAxC`Bf@H|AKx@Rv@p@Np@D`APtA?~CJj@Bn@iAfEw@nAw@~E]h@i@|A[j@g@XeA`AQ^K~@T~BFrCk@lImAnDy@\\WZCn@Px@?\\{ClK]h@aAb@UZ]tAk@r@{@fCY`Bc@tAo@`AIn@BhBGd@eBzDh@CNK?Im@\\kAZWNCj@B\\In@mAtCc@zAKh@AdAg@zAg@t@Ov@g@hAIl@iAvAGP?l@Kn@Rd@\\DbBq@~@o@T\\H^zAbAh@fAvBlBd@PjBAl@NFN?SNB?|AN^zBnAl@h@m@jCa@n@BTLHdATh@Zr@x@dA\\JHc@bB}AtIWt@o@dBEd@Ql@NHCGGDSl@s@nDwAxHD^JLdIdCDRi@pC@f@\\VdB^n@X?RoAtGiA`FBAm@nDsA`Hm@~B@P`@L|AdApFdCpBpArDnB`BfAJj@NZx@f@jARRa@Q@@C",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4409185572",
        "average_speed": 4.22,
        "max_speed": 9.4,
        "average_temp": 30,
        "average_watts": 61.2,
        "kilojoules": 231.6,
        "device_watts": false,
        "has_heartrate": true,
        "average_heartrate": 119.0,
        "max_heartrate": 153.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 170.5,
        "elev_low": 131.1,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Walk",
        "distance": 1611.7,
        "moving_time": 1425,
        "elapsed_time": 1442,
        "total_elevation_gain": 25.0,
        "type": "Walk",
        "id": 4120238201,
        "external_id": "garmin_push_5599537681",
        "upload_id": 4408719366,
        "start_date": "2020-09-27T15:35:37Z",
        "start_date_local": "2020-09-27T10:35:37Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.253361,
            -97.760286
        ],
        "end_latlng": [
            30.242835,
            -97.762299
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.253361,
        "start_longitude": -97.760286,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 2,
        "photo_count": 0,
        "map": {
            "id": "a4120238201",
            "summary_polyline": "ozswDxxtsQFA\\?XPJ?^LZNHRAJa@xALZ^^RH^Zf@Jn@Xb@h@FD\\HVDZa@PMHQZAH@dAj@t@ZTPLHZDXNbAn@P?dAr@JJr@\\XJVNTVnB`A`@XFHLLD?DD?KJ_@Hc@Pg@F_@Rk@DCT?JETAVJN?HSBk@Re@b@}BRSPER?\\JFAP}A`@cBDMXWNGr@XvBnA`@TTFJHh@VXRZTH^Lb@PNLBh@^XDb@B",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4408719366",
        "average_speed": 1.131,
        "max_speed": 1.6,
        "average_cadence": 54.7,
        "average_temp": 30,
        "has_heartrate": true,
        "average_heartrate": 112.1,
        "max_heartrate": 152.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 130.4,
        "elev_low": 102.6,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Run",
        "distance": 3220.8,
        "moving_time": 1502,
        "elapsed_time": 1693,
        "total_elevation_gain": 28.0,
        "type": "Run",
        "workout_type": null,
        "id": 4120094544,
        "external_id": "garmin_push_5599396692",
        "upload_id": 4408567974,
        "start_date": "2020-09-27T15:07:08Z",
        "start_date_local": "2020-09-27T10:07:08Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242957,
            -97.762262
        ],
        "end_latlng": [
            30.253485,
            -97.760022
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242957,
        "start_longitude": -97.762262,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 2,
        "photo_count": 0,
        "map": {
            "id": "a4120094544",
            "summary_polyline": "myqwDdeusQs@IYMQOW_@Ok@SW{@e@YUwBgA_Aa@s@a@YK{@i@kDkBm@a@w@_@y@q@WC_@Q]UYYWIg@[WGi@_@_By@[A_AB]AcCUMJa@jAQ`@ODGAYS}@We@AMBEOQO[M}@i@c@Qs@a@[[UK[G@ACBqA{@cDaBs@c@]E[Ks@_@kBm@cAa@{@c@o@c@y@_@WSK@OYUQ_@Go@Uy@i@K@GCW]eAo@m@SSAQRa@hAu@fBOh@Kn@Ev@@JFL\\P~@HF@HFBZSl@_@b@c@|@AZDTJNJRj@Xd@C^GVQt@KPKf@KHEP@h@PDEEBINSRMn@HRf@d@ZNXVXPj@XXFTVp@Nd@QXPF?d@P^z@dAl@PFT@HG@EAGKE@Gj@IrAj@`Bx@x@b@XX",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4408567974",
        "average_speed": 2.144,
        "max_speed": 3.0,
        "average_cadence": 84.0,
        "average_temp": 29,
        "has_heartrate": true,
        "average_heartrate": 138.7,
        "max_heartrate": 160.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 122.2,
        "elev_low": 93.2,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Afternoon Ride",
        "distance": 21301.4,
        "moving_time": 3823,
        "elapsed_time": 3951,
        "total_elevation_gain": 162.0,
        "type": "Ride",
        "workout_type": null,
        "id": 4116590772,
        "external_id": "garmin_push_5595818564",
        "upload_id": 4404847748,
        "start_date": "2020-09-26T21:35:12Z",
        "start_date_local": "2020-09-26T16:35:12Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242796,
            -97.762211
        ],
        "end_latlng": [
            30.242837,
            -97.762375
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242796,
        "start_longitude": -97.762211,
        "achievement_count": 24,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4116590772",
            "summary_polyline": "mxqwDzdusQi@PyAm@OQQo@a@c@kXkOqA{@yCwAyBEoCUSPs@jBU?qCeA{GaE}F}CwHqCaQmJoCeBk@As@|BsAxFQVcCk@eB\\iBe@aADYs@]Uu@Gw@YS?c@VMEK]KLSn@uAv@e@hCeB`E]jBc@t@eBvEs@vAq@|CkA`DCVDp@`@`A^rA~B`GzArCBLGPkAd@o@mAiEaKQKk@HmAtAs@fCmAfDiAxGaA~Cq@nASxAi@bBo@rCwB|EkCzCcBnCiBlDe@Z_BZgBv@aI}FMa@v@wAjBaChAuB\\KvDj@f@Vt@k@`AeBbBqE|@cApCsGx@iA`AeDrAgH^aAJw@IwADWbDoIx@{A`@sBtAoC|D_Lp@aC`@kCl@{CZwCCwAXsBT]n@Yn@qAt@q@Te@pAqEBo@eAi@AQfDwNH{ANeAr@wAz@oCf@o@t@k@Xm@xAsDbA_BnAoAp@cA^kAN_B^iB`@[j@Gf@VXb@`AsA~@\\xA_@bBDnAIfBgAvAMfJkCtAUlA_Ap@gApAo@bAy@n@y@`@w@pB_Cn@m@t@iBPuB|AqALa@nAeGfA_EtAyDlB}Ev@eDHu@A{@F_@vBwFl@iD~AsCRiAMi@c@o@K{@@q@b@cCAcCoAaAcEk@k@s@OE}AFIS?Ux@yEOO{IsCIMNk@BkAZiAh@yCIcAB_@Vg@RGxATNEFc@A}Ag@yDGwAC{GKM{B{@EQNsDOO]GAOPWlRpAvB|A|@fBpAr@`C`@xBbCnBnAjAd@|AKvAX\\XZp@d@fFEdBPfAEd@{@hDeA~AQv@OzA]pAcAlCSXwBrBExBJr@HdDi@xHK^qApDu@X]d@Cr@R~@CVwBtGa@dB_@n@iAn@q@rBc@j@s@dBg@|Bk@~Aa@f@Qv@@hCI`@e@nAs@nAg@Te@f@Bj@Il@gC`H@dAG^]`Am@|@Ox@y@bCuBdCqATgD`Ca@`@qE|Bg@t@QlAY\\}BHsN`AgFvAmBjAgBhBiAjC_@bBORu@lCq@jDMxAaBjAUl@O|@Ap@p@r@f@b@hBh@LhAUr@URmA|BENXb@WfAe@~@?TP~@v@h@Tb@nEbFH@Vo@h@s@r@SNDBLGVlKrFfK|FbHhC|N`IvIhDzE|BZVAh@ZZ~OzITCFMjAqFXKxHvEX`AVZv@\\p@H",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4404847748",
        "average_speed": 5.572,
        "max_speed": 11.1,
        "average_temp": 31,
        "average_watts": 108.4,
        "kilojoules": 414.4,
        "device_watts": false,
        "has_heartrate": true,
        "average_heartrate": 151.1,
        "max_heartrate": 172.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 238.6,
        "elev_low": 166.2,
        "pr_count": 14,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Lunch Walk",
        "distance": 2542.6,
        "moving_time": 2225,
        "elapsed_time": 2359,
        "total_elevation_gain": 40.0,
        "type": "Walk",
        "id": 4115678717,
        "external_id": "garmin_push_5594970833",
        "upload_id": 4403872832,
        "start_date": "2020-09-26T16:52:23Z",
        "start_date_local": "2020-09-26T11:52:23Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.261737,
            -97.752407
        ],
        "end_latlng": [
            30.242842,
            -97.76222
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.261737,
        "start_longitude": -97.752407,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 2,
        "photo_count": 0,
        "map": {
            "id": "a4115678717",
            "summary_polyline": "ynuwDpgssQBMf@Rr@p@LD?FNDFLJFZ\\Vj@DR\\^@@D?CPd@QZERFJILs@N?LE^HBF?RAJKVBAGH\\BZCNLn@JXJVXL@NTPJRFBBBFfAl@BDx@Tj@\\HJpBdANNJDF@ACNC?BTLADd@^r@ZLNL?NLl@X`@L?HPLn@Rj@VhCh@TTb@LJV^XRBl@VDJA@LJH@TPT@LFTRB?A?`@TTFZTTDPHNJ\\`@HEL?n@Zd@XJPLFCB@@z@TDDFNV@TFHCDKN@XCHW?M^kAPA^Hr@HPCn@J\\Mh@DZXb@Jn@^\\JDBDHLDNAX\\LH\\LHH@B\\RBF`AZ\\\\JBVTRBVJj@ZHF^PRVh@V^T\\Ln@f@TDVLpAfA^Jd@Xn@Pp@d@VHf@f@HVJLHPRNHJTFPJ@BCAD@C??@`@H\\?BQLCCBI@GC",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4403872832",
        "average_speed": 1.143,
        "max_speed": 2.9,
        "average_cadence": 53.9,
        "average_temp": 33,
        "has_heartrate": true,
        "average_heartrate": 122.5,
        "max_heartrate": 143.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 165.4,
        "elev_low": 127.2,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Lunch Run",
        "distance": 5523.8,
        "moving_time": 2557,
        "elapsed_time": 2813,
        "total_elevation_gain": 28.0,
        "type": "Run",
        "workout_type": null,
        "id": 4115459859,
        "external_id": "garmin_push_5594759808",
        "upload_id": 4403641894,
        "start_date": "2020-09-26T16:05:14Z",
        "start_date_local": "2020-09-26T11:05:14Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242994,
            -97.762315
        ],
        "end_latlng": [
            30.261781,
            -97.752024
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242994,
        "start_longitude": -97.762315,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 2,
        "photo_count": 0,
        "map": {
            "id": "a4115459859",
            "summary_polyline": "uyqwDneusQsAk@UWYu@sA}@yAu@oBgAs@i@K[Py@Vu@VyAv@eDHo@H]PeA@GBACAFIJu@b@aBfAkAJIZILYF]|@{CT]Tu@jAsC?Gp@sBd@gAp@mBFsALOPi@p@eBFY`A_CJa@b@kARs@\\y@Ng@Vo@lAiDl@yAFYACSIaBMq@]eCqBkBiCk@i@]M[ESOM[G]OS[[]S_@CuARoA[a@Q[A[D[@]A]Io@DWDSPWNUAq@_@c@E[@_@GIELQC[ZCf@BCCMHQDQAKDALMDOC_@}@Gg@Ak@OQWCYFc@PSPOBc@?KUSUSOOWQQ?u@Jg@IUAy@I[E?ACD@?GMSC_AE_@IYIIWC_@Ba@AWB]@]Ia@UuAcAs@iBWSc@UWG_@i@@AKIOUQ@[TeCtAWMK]FWAWCCi@Mk@Fk@P_Aj@u@x@s@TQVeB|@{@n@aAf@QVKXUbASN[N[FUACAi@?}AVgBFe@La@Cm@@a@D_@LkBHc@He@Vw@\\{A`@m@j@gBr@UR]P]XQVS\\CLe@~@k@zAOXIt@k@p@EZHn@?rAk@jB?j@ONSH]XUFWNAV@ZYzAD`@DBH?LLP`@VLXLhALHTFf@?`@m@x@IXk@`AK\\ATNXJJ@BMV?LMTc@fAFd@",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4403641894",
        "average_speed": 2.16,
        "max_speed": 3.0,
        "average_cadence": 83.9,
        "average_temp": 30,
        "has_heartrate": true,
        "average_heartrate": 147.8,
        "max_heartrate": 175.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 129.2,
        "elev_low": 83.4,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Afternoon Walk",
        "distance": 1482.0,
        "moving_time": 1119,
        "elapsed_time": 1198,
        "total_elevation_gain": 14.0,
        "type": "Walk",
        "id": 4111374662,
        "external_id": "garmin_push_5590651850",
        "upload_id": 4399311245,
        "start_date": "2020-09-25T19:04:36Z",
        "start_date_local": "2020-09-25T14:04:36Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.253704,
            -97.75702
        ],
        "end_latlng": [
            30.242822,
            -97.762188
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.253704,
        "start_longitude": -97.75702,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4111374662",
            "summary_polyline": "s|swDjdtsQNFDAVVp@b@PR`@PDEBBh@^TFZRl@b@VNd@J|A|@~@\\r@d@~A\\XN\\JPL`@Pb@L`@T\\FNJr@f@d@TLPHTPLb@Pz@h@d@Jf@`@d@VZH^^v@Xf@Zb@`@l@Rd@b@n@THFFAHWZsBd@m@D]DONGNBXLTR~@l@b@N^Td@L\\NVVXTPVFh@NRZX`AXb@?FEDIB?AD?GCE",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4399311245",
        "average_speed": 1.324,
        "max_speed": 1.8,
        "average_cadence": 56.4,
        "average_temp": 33,
        "has_heartrate": true,
        "average_heartrate": 127.6,
        "max_heartrate": 135.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 165.2,
        "elev_low": 149.8,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Afternoon Run",
        "distance": 3223.6,
        "moving_time": 1666,
        "elapsed_time": 2104,
        "total_elevation_gain": 37.0,
        "type": "Run",
        "workout_type": null,
        "id": 4111327020,
        "external_id": "garmin_push_5590598977",
        "upload_id": 4399259692,
        "start_date": "2020-09-25T18:29:09Z",
        "start_date_local": "2020-09-25T13:29:09Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.243075,
            -97.762271
        ],
        "end_latlng": [
            30.253942,
            -97.756889
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.243075,
        "start_longitude": -97.762271,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4111327020",
            "summary_polyline": "ezqwDfeusQg@Y]MQSc@_Am@g@gDsBcCmAe@[o@Yy@c@[GWOq@m@]S[GKTOl@q@nDKPYGc@Q{@o@}@c@kA{@O?OTKb@u@lEKRE?uA_AWIc@][Ka@SWQSUe@S{AaAq@Yu@k@qAg@{@k@i@c@}@[w@e@_@K_@Le@x@g@lAUTSEKGqA{@_@OUJSCE@CEE?^RMVI?BDM?CDM?c@Kc@m@Wg@YYG?QMSWQ@IFQDWB]OYUYCe@Ko@c@KMOEEMW[SMBGAIAAI@G]AEJCP]NMFMACIEM?QCGBEHMCk@TSBQEOBQHE?WHI?[NABK@MQQAQOGAGW@BIAGa@D_@Vq@n@iAHEDKDA`AiCHIDBA@h@}B\\w@LKF@x@d@pA~@n@T@CB?XTNRH@TLPRRHf@Lf@V`@XJBRB^N`@Ff@R`@JLPX?NIb@LJ^hAv@",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4399259692",
        "average_speed": 1.935,
        "max_speed": 3.8,
        "average_cadence": 74.9,
        "average_temp": 29,
        "has_heartrate": true,
        "average_heartrate": 142.2,
        "max_heartrate": 165.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 121.6,
        "elev_low": 90.2,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Afternoon Walk",
        "distance": 2191.5,
        "moving_time": 1974,
        "elapsed_time": 2094,
        "total_elevation_gain": 37.0,
        "type": "Walk",
        "id": 4107525829,
        "external_id": "garmin_push_5586717803",
        "upload_id": 4395195662,
        "start_date": "2020-09-24T18:35:41Z",
        "start_date_local": "2020-09-24T13:35:41Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.259814,
            -97.753651
        ],
        "end_latlng": [
            30.242811,
            -97.762187
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.259814,
        "start_longitude": -97.753651,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 2,
        "photo_count": 0,
        "map": {
            "id": "a4107525829",
            "summary_polyline": "ybuwDjossQRO@CDBAA?E^VDMADBAL@\\IVRP^LLb@XRR^PTPJBLFVX^Jn@^JHNFRBb@ZPBTDx@n@J@JJd@Tr@b@d@PRLl@VVTzBt@NNPBbA^H?VPr@V\\P^FPJRV~BxANDtA`Av@VTNVHpAt@f@THHFKJB^ZRLRFJFPAHMPeANWN[JEH?`@JL?^LRCb@DVI^?b@BbBdAD@n@^RF|@p@RHN@f@^p@XNJd@PjC|A\\PVHr@`@VF^\\ZLZPnAd@TP^PRRXLh@`@n@\\`@ZLLBXd@p@x@`@?B@Ax@LFO@K",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4395195662",
        "average_speed": 1.11,
        "max_speed": 2.2,
        "average_cadence": 55.1,
        "average_temp": 30,
        "has_heartrate": true,
        "average_heartrate": 122.0,
        "max_heartrate": 166.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 176.0,
        "elev_low": 139.6,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Lunch Run",
        "distance": 8056.2,
        "moving_time": 3634,
        "elapsed_time": 4059,
        "total_elevation_gain": 55.0,
        "type": "Run",
        "workout_type": null,
        "id": 4107524843,
        "external_id": "garmin_push_5586717179",
        "upload_id": 4395194537,
        "start_date": "2020-09-24T17:27:42Z",
        "start_date_local": "2020-09-24T12:27:42Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.243075,
            -97.762273
        ],
        "end_latlng": [
            30.259609,
            -97.753297
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.243075,
        "start_longitude": -97.762273,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 2,
        "photo_count": 0,
        "map": {
            "id": "a4107524843",
            "summary_polyline": "ezqwDfeusQWGo@c@i@mAuA{@_Ac@cAs@_@Qo@_@Y[G_@JgAf@uBHc@Z}@VcAN}@b@wAAE?GCCFe@VuAJe@`@c@d@]DKXODGV_ATg@h@wBDBFGLWVq@No@z@uBPq@?Ct@cB@CC?@OJa@^mADC@a@Fe@d@_Al@}AJOn@uBTa@Pw@x@yBBQAAk@g@WO?@VTZNTHDCd@uARa@VcA^eARc@Tm@BOOQ_BQmAq@[W[QQSWKUW}@}AiAuA[Oo@SOM]_ASY_@Oc@EeAPOAUAs@SYM]E]Ae@Du@Ik@AI@YJ]RSFWESQE_@[_@SKa@AAGFBCB@E?BWBGB?TA@SBAAQYGSKa@Cg@M_@UEa@DeAl@i@GU]SGMKEc@MYG_@DaA?i@Kg@?KKSG_@Ai@G_@GUIGYEg@?uAH_@Im@e@aAk@MWQkAMUeAe@[SOQCIGIA@KMSGOD_@Vc@P_@FWLQPSCKIGULa@@}@BUv@_AViA\\aAJe@B]PWVOf@eBFg@Bi@Fc@n@gBn@sA\\iAAKD[FSn@k@`@Wb@SJYJaALLDBHMRCLG\\CXHJMR?b@UsAl@i@RyAZsG`AcD\\I?@E`@Ih@E@@_@DOD_Ar@M`@e@l@Ep@Kt@Of@WPm@p@e@p@aB`Bu@jAk@d@iAh@w@~@kAbAU\\e@HaAFy@TIECMBG?HCFe@NUVcCj@[PMJa@LeAJ[Ly@j@_@Jy@L[@i@I]AS@SFg@X[Bo@c@KAWXg@v@KGGSYUIEE?e@FMDYNQTK~@IRG\\E`A]|@]d@SNu@b@k@j@Sf@_@j@Wl@i@v@a@v@M^A`@EZULER@Fo@j@c@~@o@lB_@v@G`@Mb@If@AjAi@rAY|AM^Mv@GYBg@VyAJK^Op@FxA\\zAd@dAT`@V`@P`@D\\JZTXLp@L^LQx@AlAHd@@\\M\\GVSLc@z@Qf@Gb@ELNRFLITCTKXk@fAH~@R\\ZTRTVh@d@Fj@RPZFVVp@RTJ?TMTi@\\[n@TXFPEH@DB@F",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4395194537",
        "average_speed": 2.217,
        "max_speed": 3.3,
        "average_cadence": 84.6,
        "average_temp": 28,
        "has_heartrate": true,
        "average_heartrate": 149.4,
        "max_heartrate": 175.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 130.2,
        "elev_low": 84.0,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Ride",
        "distance": 21561.2,
        "moving_time": 4727,
        "elapsed_time": 4926,
        "total_elevation_gain": 527.0,
        "type": "Ride",
        "workout_type": null,
        "id": 4102669782,
        "external_id": "garmin_push_5581643162",
        "upload_id": 4390082139,
        "start_date": "2020-09-23T15:26:17Z",
        "start_date_local": "2020-09-23T10:26:17Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242977,
            -97.762258
        ],
        "end_latlng": [
            30.24281,
            -97.762338
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242977,
        "start_longitude": -97.762258,
        "achievement_count": 12,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 2,
        "photo_count": 0,
        "map": {
            "id": "a4102669782",
            "summary_polyline": "qyqwDbeusQmAa@w@yAWY}IuEwJ{F_EyBwCwAqCEuB]o@zBQTUGuBw@uRkKsGcCyT{Li@EgCzKQRm@Mg@k@a@O[?sA\\sAc@oACo@}@QIs@A_A]Y?_@VKGCU_B|ESLGl@KBCe@KFmBvDc@pBw@pAqChHS|AwAnELrAhEtKz@fBRf@ANiAh@QG}@aB_CqFkAuBUI_@PaAbBuBhHmBxIeBvDO`Bg@zAw@fDmArCwAlBcA|@yEjIg@\\_B^_Aj@OTRREQJ?oJsGV_AfAyBn@s@zAcCXGxC\\fA`@h@c@dAsBtAoDhAqAhAkDl@{@dAiBfAiD|BmKDc@I}@Dc@xBuGnAiCf@sBp@kAfAoC~CsITqAb@aAb@eCd@cB`@kECeBf@yBJSp@[h@sA~@_Az@qCj@aCEO_AYCSd@eCbCgJFcBLcAfB}EVg@rAyAXiAbCgFR[rAcAl@{@\\cAh@yDR[f@Sn@Hh@n@`AoAdAXxAg@dBFhAIz@i@ASQ@NFnC]fA_@bBaA~Cw@zAIfBmAr@aAxAs@jAgAhAgBlCyC~@yBAMxBqDRaBl@gBjAuGl@{AZoA|AoDjA_ERaA@aB`CeGf@cD~@yAr@{BMw@g@s@IcADo@j@eC?i@Mm@UWaAa@cDaAe@AoARs@o@{@[GSxAiGq@a@uCw@qCgAJ}@By@XcAh@}CMoALg@LU\\IzAXLGBe@EuBc@eCKwA?mHKSyBaACYLiBAiAi@I@c@ICGHF?ANP[P@dRhAbBjApA~BvAr@tB`@j@b@dBpBjBdAh@VbCCdAXp@n@FRXfE?jBNvBeAvDaAbBe@|CcBxEkCjCMzAN~@NvDc@dHu@lCk@pA}@`@Wd@@t@Nl@A`@wBhHKt@[x@uAx@UXg@`Ba@`@cAbCaA`Es@fAEp@F|AE^w@~Bi@v@?HJ?@PVDaANq@Z{@pDqApDCfBo@`B]Z_AzDmCzCiAV_CjBkAx@yEbCSb@SlAm@l@mEFoC^yBFmDj@oEpAeFbEs@tAc@vBiA|Ds@dFsAfAg@x@KbBxAtAdBd@LbAM`Ac@`@cAzBXj@S|@Ub@?vAP`@f@d@f@fAjChDb@BjAuAfACFHI^zE`C~EtCrItEpFbBlPdJ|MdFvBnAFLEx@PAI@FBAKIDLAI?R@Z^dJxExClBT@NYdAiFJOP?`@`@tGpDXjATR|@b@x@H",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4390082139",
        "average_speed": 4.561,
        "max_speed": 8.8,
        "average_temp": 25,
        "average_watts": 130.3,
        "kilojoules": 616.1,
        "device_watts": false,
        "has_heartrate": true,
        "average_heartrate": 125.5,
        "max_heartrate": 159.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 123.6,
        "elev_low": -9.8,
        "pr_count": 1,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Run",
        "distance": 5103.7,
        "moving_time": 2260,
        "elapsed_time": 2415,
        "total_elevation_gain": 20.0,
        "type": "Run",
        "workout_type": null,
        "id": 4094291086,
        "external_id": "garmin_push_5572694903",
        "upload_id": 4381264248,
        "start_date": "2020-09-21T15:41:21Z",
        "start_date_local": "2020-09-21T10:41:21Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242979,
            -97.762254
        ],
        "end_latlng": [
            30.259658,
            -97.753532
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242979,
        "start_longitude": -97.762254,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4094291086",
            "summary_polyline": "qyqwDbeusQ_AUWKWU[aAWKwAaAcAe@}@m@q@Uc@UWAQRBDIb@w@rDA@KAwAw@cAo@[Mg@WiAu@o@W@AqBaAa@YOOo@a@G]EGi@SaAk@qAm@iA_@YM{Ag@w@]yAc@o@[eAu@s@[mAw@s@Yo@g@a@Qq@g@w@[aB{@aA[QOWIiDgAkDkBq@i@c@OmAo@MCc@UiAs@o@[a@MYOUQWMGIk@[QUKIKAQWGESHa@ICB_AjC]xAe@|ACXCHIHy@IaAY]@q@^K@_@AaA_@YEm@DWMYc@[Y]C[?]IYMWCQ@WCSEMN]hAQVId@Qb@SZS|@S\\IDMBa@EEB{@[a@UwAoAqAwAO?ON@PNNH@PGBGDQIIS@EBGRFLJBH]\\cATeBNuA?k@@UC_B\\kBPYn@]d@aAR[l@g@N[x@}Bb@oBGWaAc@CMF_@b@mB`@eAD]Q_@AS`@mBHQf@Ud@HfGvAdD~@jBp@dBt@HAXFlAf@`B~@FHD^v@jBRnA?`@C`@Md@Kj@GlAGj@K`@OhAK`@Gh@[v@SZ@D",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4381264248",
        "average_speed": 2.258,
        "max_speed": 3.2,
        "average_cadence": 85.2,
        "average_temp": 24,
        "has_heartrate": true,
        "average_heartrate": 142.2,
        "max_heartrate": 159.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 122.8,
        "elev_low": 85.6,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Run",
        "distance": 1615.7,
        "moving_time": 710,
        "elapsed_time": 817,
        "total_elevation_gain": 33.0,
        "type": "Run",
        "workout_type": null,
        "id": 4088477302,
        "external_id": "garmin_push_5566495863",
        "upload_id": 4375094936,
        "start_date": "2020-09-20T15:56:46Z",
        "start_date_local": "2020-09-20T10:56:46Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.24287,
            -97.762324
        ],
        "end_latlng": [
            30.241644,
            -97.768851
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.24287,
        "start_longitude": -97.762324,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4088477302",
            "summary_polyline": "}xqwDpeusQBLFHnChApAr@\\VRTA\\Mp@CX`@RTNTXb@r@VXr@\\j@Rh@ZjBx@FFALA?PHJLb@JtCxAvA^r@Vr@^?FC@?ADAJBx@`@Jr@LZZ`@Sp@INWLg@Ga@MgAg@g@_@mAq@QEOKcAe@s@U{Ay@QE[QEBEZgBtF_@fBs@~BMTm@BKFSd@IAWSGA",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4375094936",
        "average_speed": 2.276,
        "max_speed": 2.8,
        "average_cadence": 84.5,
        "average_temp": 27,
        "has_heartrate": true,
        "average_heartrate": 141.1,
        "max_heartrate": 165.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 155.4,
        "elev_low": 120.2,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Run",
        "distance": 3041.9,
        "moving_time": 1418,
        "elapsed_time": 1596,
        "total_elevation_gain": 17.0,
        "type": "Run",
        "workout_type": null,
        "id": 4083031173,
        "external_id": "garmin_push_5560975053",
        "upload_id": 4369301437,
        "start_date": "2020-09-19T15:38:17Z",
        "start_date_local": "2020-09-19T10:38:17Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.243038,
            -97.762321
        ],
        "end_latlng": [
            30.25139,
            -97.758466
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.243038,
        "start_longitude": -97.762321,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4083031173",
            "summary_polyline": "}yqwDpeusQuAi@OWYw@YU_@O}@q@QUiCmA[Ya@MQJCFATMb@?Cq@`DENIA}@m@G?}@e@SOoBgAu@]}CgB}Au@KQAUiAu@gB}@mA_@UOUIUQgAe@UOo@C}@Y{BoAw@]u@q@IACBmAhDi@z@qAo@]W}As@oAs@a@[GA_Ag@c@]y@e@_@OsDwBw@MaAIa@Qy@MqAMa@?OIAEb@yAf@kAl@cBLYBAJBTLTH`@VVF\\Vx@\\C@TRp@VJ@t@d@`@Pv@j@l@N^NDF\\Hx@Xb@Rh@PdBdAbCrAbAf@F@hCvAf@Rn@^VJd@\\?BFB",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4369301437",
        "average_speed": 2.145,
        "max_speed": 3.3,
        "average_cadence": 79.1,
        "average_temp": 27,
        "has_heartrate": true,
        "average_heartrate": 143.8,
        "max_heartrate": 166.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 123.2,
        "elev_low": 102.0,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Run",
        "distance": 5368.7,
        "moving_time": 2438,
        "elapsed_time": 2823,
        "total_elevation_gain": 23.0,
        "type": "Run",
        "workout_type": null,
        "id": 4073434313,
        "external_id": "garmin_push_5551029203",
        "upload_id": 4359172103,
        "start_date": "2020-09-17T14:43:02Z",
        "start_date_local": "2020-09-17T09:43:02Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.243002,
            -97.762266
        ],
        "end_latlng": [
            30.26211,
            -97.750771
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.243002,
        "start_longitude": -97.762266,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 2,
        "photo_count": 0,
        "map": {
            "id": "a4073434313",
            "summary_polyline": "wyqwDdeusQS@k@WWIY[Mi@SUu@g@]Ys@_@wAaAwAo@Q_@?Wt@uCd@}BPgABGDDACX{@RgADMCED@CGB@EGAUVo@Jm@Zk@Z]VUf@[Xq@h@}AVaAd@cAFe@N]HI@I\\w@`AwCtAiDDQ?GHFAC@gAJ]T]h@mAHg@N_@b@iBXYFOCA?Eh@wA^{AdAyBPe@Nq@\\aAf@eAAEDICK_@MgAKYI{BeA}@m@]m@Yo@o@{@c@][Q[IUQWi@QOYa@UUUKMEYD_@JY@u@Iw@_@YEwA?WEaA@]b@YJYIWKIYKQq@_@DBE@E??CGEGB?CEDSDICDPC@QBMC]y@GoACGIGk@?WFMFYZG@O?SEWWQOKCGI[aAIuCGQAWMYCa@SmAQOgA@YD[Aa@IaBkAW_@a@cAUYgAq@][CMKMSIWJu@b@{@Xa@TG?K?GEGWFk@AKKEYAk@?YFWJc@VqAhAe@NYXYPoAp@kAt@a@JUXQ^SnAMN[LaAFYC[FeADoAVw@Ak@JyA@_AJ}AJQFEDSJgBd@]P_@JWNILw@`@e@\\OH[Xo@b@W\\e@|@a@lA_@`BSh@]xA@ZEr@Ol@_@v@Ih@Af@_Av@_@NMLSt@OfAQZy@l@EFO^EZYv@Il@Yx@G^BNL\\XHb@Fb@?t@F",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4359172103",
        "average_speed": 2.202,
        "max_speed": 3.5,
        "average_cadence": 82.6,
        "average_temp": 30,
        "has_heartrate": true,
        "average_heartrate": 152.2,
        "max_heartrate": 179.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 129.0,
        "elev_low": 82.2,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Run",
        "distance": 2029.1,
        "moving_time": 937,
        "elapsed_time": 1035,
        "total_elevation_gain": 4.0,
        "type": "Run",
        "workout_type": null,
        "id": 4058614472,
        "external_id": "garmin_push_5535668138",
        "upload_id": 4343566618,
        "start_date": "2020-09-14T14:15:03Z",
        "start_date_local": "2020-09-14T09:15:03Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.24285,
            -97.762396
        ],
        "end_latlng": [
            30.258347,
            -97.754325
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.24285,
        "start_longitude": -97.762396,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4058614472",
            "summary_polyline": "yxqwD~eusQUKIGaAWYSOWSm@YMiBmAa@a@yBiA[U@Ac@Ou@e@]KiBiA_@KSDKZEp@}@vCm@Sa@CWEa@QY[[Wk@[AI{Ay@Wk@gAi@GMeBcA]Ca@G]Oc@I_Ac@WGc@WeBk@_@YeAi@w@[[UcB_AAA@?IGm@_@uDmBi@]]QsAa@WK]Gw@WgAc@_D_Bs@g@_Ai@QQOEIIQE_@Us@[g@[UYK?OG",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4343566618",
        "average_speed": 2.166,
        "max_speed": 2.9,
        "average_cadence": 82.4,
        "average_temp": 28,
        "has_heartrate": true,
        "average_heartrate": 135.9,
        "max_heartrate": 154.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 121.4,
        "elev_low": 95.4,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Run",
        "distance": 3227.7,
        "moving_time": 1372,
        "elapsed_time": 1413,
        "total_elevation_gain": 28.0,
        "type": "Run",
        "workout_type": null,
        "id": 4054615482,
        "external_id": "garmin_push_5531400651",
        "upload_id": 4339290365,
        "start_date": "2020-09-13T15:08:30Z",
        "start_date_local": "2020-09-13T10:08:30Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242994,
            -97.762297
        ],
        "end_latlng": [
            30.251478,
            -97.75835
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242994,
        "start_longitude": -97.762297,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4054615482",
            "summary_polyline": "uyqwDjeusQ]DELU~@]nB_@bBKP_@d@YRSDc@AQBq@?s@GcASuD{Bw@]}@e@?Ak@Um@_@_Aa@oCgBYKQMkBaAc@[g@SkAu@gAe@y@i@UKu@g@YGqAg@qBgAyAaAsAs@WSyA{@i@a@gAi@wAeAu@[s@k@i@YaAYYU]OQM[IuA_AoAq@}@Wq@IiBe@o@MkDOs@Bi@KCQPoBv@wBRa@Z_AZi@HCt@\\|ErClA\\RLVTrAl@zAdAv@V\\PfBp@~@PpAx@b@T~BtAx@l@?B?AfAf@jAl@XHb@Vf@L`@R",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4339290365",
        "average_speed": 2.353,
        "max_speed": 3.6,
        "average_cadence": 85.3,
        "average_temp": 30,
        "has_heartrate": true,
        "average_heartrate": 152.2,
        "max_heartrate": 178.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 126.2,
        "elev_low": 94.8,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Run",
        "distance": 1612.2,
        "moving_time": 741,
        "elapsed_time": 771,
        "total_elevation_gain": 34.0,
        "type": "Run",
        "workout_type": null,
        "id": 4049299664,
        "external_id": "garmin_push_5526016981",
        "upload_id": 4333675437,
        "start_date": "2020-09-12T15:39:43Z",
        "start_date_local": "2020-09-12T10:39:43Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242735,
            -97.762235
        ],
        "end_latlng": [
            30.241361,
            -97.768843
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242735,
        "start_longitude": -97.762235,
        "achievement_count": 1,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4049299664",
            "summary_polyline": "axqwD~dusQALC@FJn@b@lAn@f@P^Td@RZRhA|@|@HNFRVRLTDNDhCnAtDjBnA|@\\Pv@\\n@LxAf@n@ZRN@DCJi@f@S^Kt@Bb@FZTd@PR?JM`@ILKF_@DWA]M_B}@m@UkAq@OCeBq@g@]y@_@i@[KAOLOZg@|AU\\o@nBAZ]p@Cb@Mh@i@h@OT]|@",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4333675437",
        "average_speed": 2.176,
        "max_speed": 3.1,
        "average_cadence": 84.3,
        "average_temp": 29,
        "has_heartrate": true,
        "average_heartrate": 149.7,
        "max_heartrate": 165.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 156.4,
        "elev_low": 121.4,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Walk",
        "distance": 2346.1,
        "moving_time": 2254,
        "elapsed_time": 2449,
        "total_elevation_gain": 31.0,
        "type": "Walk",
        "id": 4049163023,
        "external_id": "garmin_push_5525881560",
        "upload_id": 4333532676,
        "start_date": "2020-09-11T15:01:56Z",
        "start_date_local": "2020-09-11T10:01:56Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.259406,
            -97.752704
        ],
        "end_latlng": [
            30.242829,
            -97.762236
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.259406,
        "start_longitude": -97.752704,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4049163023",
            "summary_polyline": "g`uwDlissQ?h@U`@GRA|@ERHJn@R`ANlAv@FL~@ZDHn@Xf@Lb@b@P@HFLVl@Rv@b@DF?FDD^JXPf@LL@b@RZb@TTNHd@LNJN@JF@Ad@RZDr@NZN`@LXXj@^NPPB`@Xd@NVNND\\R\\L^^r@T\\Xj@N\\THBTLNP\\Vb@VNDn@d@^HR?hAb@h@\\^EZRLPhAVh@Vp@d@RDDBFLRANFBB\\~@RLNDJN^LL@n@\\LDLLLB^RV^|@VFHPD`@PPFF@R^RRTD`@RBAHQ?MDSh@gBNo@R[@MFGB@LDl@j@\\DNH\\\\v@`@TDlB`A\\Jt@h@NXJ\\NVZX^Rj@PHEFYBAC?DCAFHAAIAHKCGHDHGA@GA@D@A?",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4333532676",
        "average_speed": 1.041,
        "max_speed": 1.8,
        "average_cadence": 54.0,
        "average_temp": 27,
        "has_heartrate": true,
        "average_heartrate": 117.4,
        "max_heartrate": 133.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 118.8,
        "elev_low": 86.0,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Run",
        "distance": 4854.4,
        "moving_time": 2040,
        "elapsed_time": 2227,
        "total_elevation_gain": 19.0,
        "type": "Run",
        "workout_type": null,
        "id": 4044213757,
        "external_id": "garmin_push_5520724610",
        "upload_id": 4328318726,
        "start_date": "2020-09-11T14:22:50Z",
        "start_date_local": "2020-09-11T09:22:50Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242949,
            -97.762396
        ],
        "end_latlng": [
            30.25893,
            -97.751193
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242949,
        "start_longitude": -97.762396,
        "achievement_count": 1,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4044213757",
            "summary_polyline": "kyqwD~eusQE@MKk@Kg@e@GIS}@WYQMg@UqC}AqAm@gEgC{@g@YGu@c@WCKLGRBH?LKRKZa@tBONYKkCqAwA_AMe@WU]M_CiAq@Um@[yBw@}Aa@iCyAo@c@_@Qa@K}@c@QK@?KKIAiAo@][iC{AgAWiBs@kBm@_@OeAm@oFqCoDuByAo@i@_@cAg@i@e@ABi@GEBOPSn@Sx@a@vBMZO|@@NINsAK[O]GaBZ[E[Oq@QID[DYA[WO]]Sm@C[M_@I]A_AXYPONOXOlAQd@KFKTM`@O\\[LY@c@Ky@]{@y@y@m@_@a@CK??KGKQECG?OBGTBLFDTBLKBGCUGCI?MHGHBTFFB[^w@b@gBDw@Nk@CoBA_@Vw@VuAv@u@Te@Rg@^SPMVc@x@gCb@mBAIGIi@QYQL_A\\eAZqAN]IOMYBYRiAB]LSXIVCdHlBfCd@`CjA`AZr@PTBTN~@N`@N`@VXZ@VBFj@t@Pd@LTBNBfABRAp@",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4328318726",
        "average_speed": 2.38,
        "max_speed": 3.1,
        "average_cadence": 85.9,
        "average_temp": 23,
        "has_heartrate": true,
        "average_heartrate": 153.4,
        "max_heartrate": 179.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 121.4,
        "elev_low": 83.4,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Run",
        "distance": 2704.6,
        "moving_time": 1315,
        "elapsed_time": 1519,
        "total_elevation_gain": 34.0,
        "type": "Run",
        "workout_type": null,
        "id": 4039739126,
        "external_id": "garmin_push_5516045583",
        "upload_id": 4323581957,
        "start_date": "2020-09-10T14:58:17Z",
        "start_date_local": "2020-09-10T09:58:17Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.24298,
            -97.762327
        ],
        "end_latlng": [
            30.248657,
            -97.759969
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.24298,
        "start_longitude": -97.762327,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4039739126",
            "summary_polyline": "syqwDpeusQgAa@MIOSYo@w@o@eCqAy@e@aAc@y@g@WUEYUEa@SiBgA@CBFUCeAo@g@UaAk@MCGBQp@Gb@Ar@Kl@c@nAq@rDGPKp@Uj@CBUByBiAQAMd@Y~AQn@c@IgAa@eCyAOEWOWIODCH?A]t@OHmA_@q@[QMa@O[SoAiACG@ENk@Vm@AMKM[Qq@g@qBcAy@g@o@S}@e@OKUUUIE??DKFG?KGJFANE@AC\\a@d@\\z@X\\PPFT@RYJQb@gAPi@DGJC^NJKNYNUBKLQv@sBJSB?^RNLr@XhCvA@BJB`@TdAZ^Dn@LZL|@b@t@XzA~@nAj@XRHP",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4323581957",
        "average_speed": 2.057,
        "max_speed": 4.0,
        "average_cadence": 85.2,
        "average_temp": 23,
        "has_heartrate": true,
        "average_heartrate": 146.6,
        "max_heartrate": 173.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 121.4,
        "elev_low": 94.0,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Run",
        "distance": 1612.9,
        "moving_time": 782,
        "elapsed_time": 881,
        "total_elevation_gain": 33.0,
        "type": "Run",
        "workout_type": null,
        "id": 4037148944,
        "external_id": "garmin_push_5513283645",
        "upload_id": 4320820509,
        "start_date": "2020-09-09T15:22:34Z",
        "start_date_local": "2020-09-09T10:22:34Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242885,
            -97.762293
        ],
        "end_latlng": [
            30.240554,
            -97.763701
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242885,
        "start_longitude": -97.762293,
        "achievement_count": 1,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4037148944",
            "summary_polyline": "_yqwDjeusQ@HJLfBr@xAdAn@^jAz@ZXlAP\\XXBl@X^Jh@Zz@b@XPTR^V\\JfBfA`A`@pCn@rBjABLe@^ONUn@GF?PL~@f@z@W`AOFc@GqAg@_Ak@w@Om@c@c@SIIQIED@AOOoBs@u@c@Yi@mAk@[SoAk@EM@SHSDa@FMJs@Xy@N}@Ao@GGAE",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4320820509",
        "average_speed": 2.063,
        "max_speed": 3.7,
        "average_cadence": 80.1,
        "average_temp": 28,
        "has_heartrate": true,
        "average_heartrate": 149.8,
        "max_heartrate": 178.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 154.0,
        "elev_low": 120.6,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Ride",
        "distance": 7567.6,
        "moving_time": 2107,
        "elapsed_time": 2250,
        "total_elevation_gain": 130.0,
        "type": "Ride",
        "workout_type": null,
        "id": 4022636572,
        "external_id": "garmin_push_5498166390",
        "upload_id": 4305470703,
        "start_date": "2020-09-06T15:56:21Z",
        "start_date_local": "2020-09-06T10:56:21Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242774,
            -97.762346
        ],
        "end_latlng": [
            30.242828,
            -97.762229
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242774,
        "start_longitude": -97.762346,
        "achievement_count": 3,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4022636572",
            "summary_polyline": "ixqwDteusQCFUEcA[a@U]e@GWWi@w@g@cAi@oDuBe@Qm@c@i@WmAu@cAc@i@_@m@WiAy@wAq@aBaA_@Os@g@{@e@SCyA@aBSm@CSZo@dBIBSEs@]mAa@c@[yBgA{CgB]OaFqC}@]wCcA_Bm@cBeAuC{AmAu@cAg@{A{@oAk@cCwAq@WG?IHq@fDcAtDMj@GPOFo@S]e@OGa@AQDu@ZS@[Go@[a@Gg@DSCOMWc@OMSEk@Ag@UQE[?MHILG@GCEM?QGHSn@Wt@YhA[|@Wj@U^]FEAm@M{@[}AkA_@UU_@QQSYKIEAG@IH?T@BPJD@HABC@KCKQOGJ@j@GWAMBc@Pm@v@sAR_B@cAEm@@e@b@oBBGTO^OFGd@qAn@i@f@oAT}@Te@`@cB@IEOw@_@EKBWTs@X{AVy@@MMy@\\uBRQZOF?l@LrBl@fJ~BlCbAD@BCGAa@nAI`@@PEPo@^cAfAk@dASh@KPAFXXBFKr@a@~@DjAN`@HNPF^n@RVZd@FP~@rA`@\\ZPXAf@Sr@{@Li@RQD@@DAf@HTGVAAF@t@`@f@PRDb@Rf@^XNXVPJjCtAlAv@h@T`Aj@tBbATPd@Pb@Vl@Tj@LhBl@pAf@|Av@xCfBn@XfAp@zAt@j@`@~@f@pCfAfA^tErB~A|@N?BCLy@l@gCLQRAvA|@n@XXRZJ`Ah@r@f@^NJ@zAfAtAv@l@RVR?HL?\\Nr@Vv@f@RX|@TRLz@l@DN?TBFTd@NPh@RF?^NRBHCBC?IAGFEBHGCABAAC@B?CC",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4305470703",
        "average_speed": 3.592,
        "max_speed": 9.4,
        "average_temp": 31,
        "average_watts": 99.3,
        "kilojoules": 209.1,
        "device_watts": false,
        "has_heartrate": true,
        "average_heartrate": 123.2,
        "max_heartrate": 157.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 147.6,
        "elev_low": 48.0,
        "pr_count": 1,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Morning Ride",
        "distance": 10468.0,
        "moving_time": 2600,
        "elapsed_time": 2857,
        "total_elevation_gain": 374.0,
        "type": "Ride",
        "workout_type": null,
        "id": 4022635419,
        "external_id": "garmin_push_5498165241",
        "upload_id": 4305469403,
        "start_date": "2020-09-02T14:59:53Z",
        "start_date_local": "2020-09-02T09:59:53Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242807,
            -97.762256
        ],
        "end_latlng": [
            30.242836,
            -97.762278
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242807,
        "start_longitude": -97.762256,
        "achievement_count": 8,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a4022635419",
            "summary_polyline": "oxqwDbeusQ@NED_Ba@[QKMM[Gc@IKcB}@a@OkAu@oBeAGGGUbC_KRkA\\cA?EB@@CJo@b@kBTc@z@m@LOv@iB`BgFXq@tD_KDy@FY`AkClA_EnAmD@WMQoAi@SOQG`CtADAHGFMx@{BDUAYQSIEuCyAaAm@CI@ORg@@ECO_@u@q@u@e@a@}CaBkBmAm@WeD}@YMcAQS?_@DkAP[@OCuCiAu@USMg@s@[S_@Ik@EQO@Wj@_Ah@yA?Oa@[}A_Am@[EEEW@_@Co@CSCEUIQAy@FeA@a@IsAcA_@k@_@}@c@a@sA{@KM?MCESQ[L{@l@q@Z[VEBI?OIIYAKHo@Cw@b@c@l@y@Pq@j@aBJs@HQVUHQj@}A@UEe@Dc@v@{BdAkCHaADSX[VMlAUHIBID_ABED@BHHSFGLEZAJ?PNF@LIL?NGVSRWD?BD?H[R{@^sA`@_APwDd@kEl@aAHEA@CbAMJBa@FqAh@Ox@Wp@Eb@Kh@M\\Y\\k@f@e@v@WNm@r@a@n@SR]j@k@f@}Ax@KJe@n@u@f@q@l@mALcA`@uAZWD}@Tk@Pu@^k@Bm@FMBa@VIBICAEFGDDAL[Tk@Pi@BYF{AGi@Ji@TK@[Ig@UO`@[h@MJICS[]UQAUBMDQLIJQ`@A\\M`@If@Ex@[dA]j@[X_An@@FEFgAxBm@~@m@nAYz@KHo@j@MPUd@Y~@]rAg@pA[hAC`@@n@Gx@Mr@w@`C?FBC?HIZC@GIG[?KPqAJe@XQb@CfG~AzCp@\\Xn@Pl@T@NMl@AP@jAHl@Uv@WZq@fAOj@IL?NVRDLQt@[p@AH?`ABPDLj@b@NVb@\\l@z@t@x@|CDn@GJLKL?D@B@GECB?z@f@j@b@xAp@RF|AdAbBv@`Aj@b@NdBjA\\J|BlAvAr@tBt@~@Vv@\\lAn@x@j@dD`BfGfDxBx@x@RzD|AdAj@z@f@^XCZBRDB|@l@~@d@ZThAf@nDpBxBtAZNNDPGJc@x@eEFSHMFAL@VVx@b@|BvAfBz@XnA\\\\\\Nx@T\\BFc@EC@AEJTUCNOTCEM@?B@E",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4305469403",
        "average_speed": 4.026,
        "max_speed": 9.1,
        "average_temp": 26,
        "average_watts": 184.0,
        "kilojoules": 478.3,
        "device_watts": false,
        "has_heartrate": true,
        "average_heartrate": 126.0,
        "max_heartrate": 160.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 127.6,
        "elev_low": -40.6,
        "pr_count": 3,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 25087475,
            "resource_state": 1
        },
        "name": "Lunch Ride",
        "distance": 11627.2,
        "moving_time": 2791,
        "elapsed_time": 2943,
        "total_elevation_gain": 173.0,
        "type": "Ride",
        "workout_type": null,
        "id": 3996701765,
        "external_id": "garmin_push_5472135166",
        "upload_id": 4278238378,
        "start_date": "2020-09-01T16:02:21Z",
        "start_date_local": "2020-09-01T11:02:21Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000.0,
        "start_latlng": [
            30.242691,
            -97.76244
        ],
        "end_latlng": [
            30.242818,
            -97.762208
        ],
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "start_latitude": 30.242691,
        "start_longitude": -97.76244,
        "achievement_count": 6,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a3996701765",
            "summary_polyline": "ywqwDffusQs@c@}@U]OU_@Mg@MM[UcBy@gE_C_Ac@mDqBe@Sy@o@]Os@k@eBw@uA{@[I{@i@s@i@m@E{@Bw@OeBSEB[jAQd@OLE?s@[uBq@{DmBkAo@a@[SGcFsCc@Qu@SmAg@cBk@oAi@sBkAoDyBw@]qE}BwA{@e@_@JBEGBMr@mCJw@^mAHQA@@@I?UKEI?Er@yCXaAXoAASQSm@UcB{@eAc@kC}Ao@YkCw@{EmAmF_BYEK?g@\\W|@M`A?VLVBLSb@i@jBMh@Kp@DLDDn@TLNIh@yAtEW`@c@Z]z@OXk@XOLQh@SbAEd@AvAYpD[|AQd@K|@Kl@wA~EmAxCWr@YdAy@rBKb@GL_@b@QZg@lBg@bAY|@e@fAm@dBUz@]`AERC\\Dz@?TG`@]~@a@bC[v@_@pB[hAKp@IN_@t@]z@o@|@i@~Aq@vAcAbAIPW|@g@dASr@]l@Sd@k@v@SBGA]UMGoAWk@CQEi@AYXmAzBc@d@s@pAY^Wh@_@`@D@FAPDt@t@j@`@~Aj@h@\\jBxAV@FAx@c@bB]XSn@iA`AqB|AaCt@}@|@_A`AiBdAeCTs@T}Ah@qAJq@ASB[Lk@HQ`@k@j@qATcA~@eFhAwEr@yBRi@j@y@^_@RCPDLLd@r@Rb@fBdFTd@bA~AHDfAg@@C@UMc@y@uB_@mAcAeCc@mAk@iC@i@AQDo@`AcDNoADQp@qAxAkEZe@FS`@_Cr@}@ZaAn@uARoALa@\\[d@QJ_@JYNE@RLFD?TOXCL@v@Zb@?THX^DLNV\\Dh@?d@D~@V`@El@YTEN@r@ThALHMPk@~A{GJo@DG?H?GDID?C@@@d@Xx@b@f@F^PlA~@`BfAh@T`@\\d@Xd@LJHZJ~A|@fAv@`@RtGdCzCrAv@f@~GnDt@f@x@^dAZv@`@d@HJUb@wALORGn@LdAJTFlAIVFVRlCpAt@d@`@PfAr@ZJh@`@tBdAp@f@tAn@dDjB`Bv@XRtBjA\\`@Px@\\Zl@PBCt@JNI@QAHAEID@@CA",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "from_accepted_tag": false,
        "upload_id_str": "4278238378",
        "average_speed": 4.166,
        "max_speed": 8.3,
        "average_temp": 31,
        "average_watts": 98.8,
        "kilojoules": 275.7,
        "device_watts": false,
        "has_heartrate": true,
        "average_heartrate": 130.6,
        "max_heartrate": 163.0,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 125.8,
        "elev_low": 28.8,
        "pr_count": 5,
        "total_photo_count": 0,
        "has_kudoed": false
    }
]